#!/bin/bash
FILE=report
FILET=${FILE}.tex
FILEA=${FILE}.aux
latex $FILET
bibtex $FILEA
makeglossaries $FILE
pdflatex $FILET; pdflatex $FILET
rm *.aux *.glg *.glo *.ilg *.ist *.log *.out *.toc *.acr *.gls *.idx *.blg *.bbl 2> /dev/null
