#!/bin/bash
FILE=report
FILEO=${FILE}-old.tex
FILEC=${FILE}.tex
FILET=${FILE}-diff.tex
FILEA=${FILE}.aux

latexdiff --flatten abstract-old.tex abstract.tex > abstract-diff.tex
latexdiff --flatten $FILEO $FILEC > $FILET

latex $FILET
bibtex $FILEA
makeglossaries $FILE
pdflatex $FILET; pdflatex $FILET
rm *.aux *.glg *.glo *.ilg *.ist *.log *.out *.toc *.acr *.gls *.idx *.blg *.bbl *.lof 2> /dev/null
